on: 
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  tfe:
    uses: LeiZhaoGFT/reusable-workflow/.github/workflows/callee.yaml@main
    with:
      name: mona
    secrets: inherit  
